### ISSUE TITLE
clean Parameters with macros

### ISSUE THREAD

**Issue by vendethiel** [volgar1x/photon-persist#2]
[Parameters.scala](https://github.com/Blackrush/photon-persist/blob/master/src/org/photon/common/persist/Parameters.scala) needs to die

**Comment by volgar1x** [comment]
It's defined once and for all, so no big deal IMO.

**Comment by vendethiel** [comment]
maybe we should provide ways for people to plug-in their "adapters" ?

**Comment by volgar1x** [comment]
Isn't it the goal of implicits ? You just import your own `Parameter` and that's all.

**Comment by vendethiel** [comment]
and in this case, people might want to be able to write their adapters cleanly ;)

**Comment by volgar1x** [comment]
I don't think that writing some "glue" macros will make it cleaner
